service: MONEY
frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  timeout: 10
  memorySize: 1024
  versionFunctions: false
  environment: ${self:custom.env}
  deploymentBucket:
    name: money-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
  layers:
    - {Ref: CommonUtilsLambdaLayer}
    - {Ref: PrismaClientLambdaLayer}

custom:
  env: ${file(./serverless.${self:provider.stage}.env.yml)}
  stackName: ${opt:stackName, 'dev'}
  projectName: ERP
  authorizer:
    name: authorizer
    type: request
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
  # for production
  webpack:
    includeModules: false

layers:
  commonUtils:
    name: ${self:service}-${sls:stage}-common-node_modules
    description: common node_modules
    path: ./
    compatibleRuntimes: nodejs18.x
    package:
        patterns:
          - node_modules/**
          - '!node_modules/.cache/**'
          - '!node_modules/.prisma/**'
          - '!node_modules/prisma/**'
          - '!node_modules/@prisma/**'
          - '!.build/**'
          - '!.vscode/**'
          - '!.github/**'
          - '!.vscode/**'
          - '!.webpack/**'
  prismaClient:
    name: ${self:service}-${sls:stage}-prisma-node_modules
    description: prisma client
    path: ./
    compatibleRuntimes: nodejs18.x
    package:
        patterns:
          - node_modules/.prisma/**
          - node_modules/@prisma/**
          - node_modules/prisma/**
          - '!node_modules/.cache/**'
          - '!node_modules/prisma/query_engine-windows.*' # only running on server windows
          - '!node_modules/.prisma/client/query_engine-windows.*' # only running on server windows
          - '!node_modules/.prisma/client/libquery_engine-*'
          - 'node_modules/.prisma/client/libquery_engine-rhel-*'
          - '!node_modules/prisma/libquery_engine-*'
          - '!node_modules/@prisma/engines/**'
          - '!.build/**'
          - '!.vscode/**'
          - '!.github/**'
          - '!.vscode/**'
          - '!.webpack/**'

functions:
  # - ${file(resources/warm-up.yml)}
  # - ${file(resources/functions/auth.yml)}
  - ${file(resources/functions/function.yml)}
  - ${file(resources/functions/user.yml)}