service: ERP
frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-offline
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  timeout: 10
  memorySize: 1024
  versionFunctions: false
  environment: ${self:custom.env}
  deploymentBucket:
    name: custom-deployment-bucket-erp-${self:provider.stage}
    serverSideEncryption: AES256
  layers:
    - {Ref: CommonUtilsLambdaLayer}
    - {Ref: PrismaClientLambdaLayer}
    - {Ref: AwsSDKLambdaLayer}
    
custom:
  env: ${file(./serverless.${self:provider.stage}.env.yml)}
  stackName: ${self:service}-${self:provider.stage}
  authorizer:
    name: authorizer
    type: request
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization

	
layers:
  commonUtils:
    name: ${self:service}-${sls:stage}-common-node_modules
    description: common node_modules
    path: ./
    compatibleRuntimes: nodejs16.x
    package:
        patterns:
          - node_modules/**
          - '!node_modules/.cache/**' 
          - '!node_modules/aws-sdk/**'
          - '!node_modules/.prisma/**'
          - '!node_modules/prisma/**'
          - '!node_modules/@prisma/**'
  prismaClient:
    name: ${self:service}-${sls:stage}-prisma-node_modules
    description: prisma client
    path: ./
    compatibleRuntimes: nodejs16.x
    package:
        patterns:
          - node_modules/.prisma/**
          - node_modules/@prisma/**
          - node_modules/prisma/**
          - '!node_modules/prisma/query_engine-windows.*' # only running on server windows
          - '!node_modules/.prisma/client/query_engine-windows.*' # only running on server windows
          - '!node_modules/.prisma/client/libquery_engine-*'
          - 'node_modules/.prisma/client/libquery_engine-rhel-*'
          - '!node_modules/prisma/libquery_engine-*'
          - '!node_modules/@prisma/engines/**'
  awsSDK:
    name: ${self:service}-${sls:stage}-aws-sdk-node_modules
    description: AWS SDK
    path: ./
    compatibleRuntimes: nodejs16.x
    package:
        patterns:
          - node_modules/aws-sdk/**    

functions:
  # - ${file(resources/warm-up.yml)}
  - ${file(resources/functions/auth.yml)}
  - ${file(resources/functions/customer.yml)}
  - ${file(resources/functions/inventory.yml)}
  - ${file(resources/functions/invoice.yml)}

# resources:
  # - ${file(resources/sqs.yml)}
  # - ${file(resources/role.yml)}
package:
  patterns:
    - '!node_modules/**'