service: ERP
frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-webpack-prisma

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  timeout: 10
  memorySize: 1024
  versionFunctions: false
  environment: ${self:custom.env}

custom:
  env: ${file(./serverless.${self:provider.stage}.env.yml)}
  stackName: ${opt:stackName, 'dev'}
  projectName: 
  # prisma:
  #   installDeps: false
  #   # prismaPath: prisma/schema.prisma
  #   dataProxy: false
  webpack:
    includeModules: true
    # packagerOptions:
    #   scripts:
    #      - prisma generate
  authorizer:
    name: authorizer
    type: request
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization

functions:
  # - ${file(resources/warm-up.yml)}
  # - ${file(resources/functions/auth.yml)}
  - ${file(resources/functions/customer.yml)}
  # - ${file(resources/functions/inventory.yml)}
  # - ${file(resources/functions/invoice.yml)}

# resources:
  # - ${file(resources/sqs.yml)}
  # - ${file(resources/role.yml)}
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'