service: passii
configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  timeout: 10
  versionFunctions: false
  environment: ${self:custom.env}
  iam:
    role: myDefaultRole

custom:
  env: ${file(./serverless.${self:provider.stage}.env.yml)}
  stackName: ${opt:stackName, 'dev'}
  projectName: ${opt:projectName, 'passii'}
  esbuild:
    minify: false
    sourcemap: linked
    keepNames: true
  authorizer:
    name: authorizer
    type: request
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization

functions:
  - ${file(resources/warm-up.yml)}
  - ${file(resources/functions/auth.yml)}
  - ${file(resources/functions/otp.yml)}

resources:
  - ${file(resources/sqs.yml)}
  - ${file(resources/role.yml)}