service: passii
# Framework version constraint (semver constraint): '3', '^2.33'
frameworkVersion: "3"

# Configuration validation: 'error' (fatal error), 'warn' (logged to the output) or 'off' (default: warn)
# See https://www.serverless.com/framework/docs/configuration-validation
configValidationMode: error
plugins:
  # - serverless-bundle
  - serverless-esbuild
  - serverless-offline
  # - ./plugins/stacks/split-stacks.js

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  timeout: 10
  versionFunctions: false
  environment: ${self:custom.env}
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
        # identitySource: method.request.header.Authorization
custom:
  env: ${file(./serverless.${self:provider.stage}.env.yml)}
  stackName: ${opt:stackName, 'dev'}
  projectName: ${opt:projectName, 'passii'}
  esbuild:
    minify: false
    sourcemap: linked
    keepNames: true
  # serverless-offline:
  #   ignoreJWTSignature: true
functions:
  - ${file(resources/functions/auth.yml)}
  - ${file(resources/functions/otp.yml)}
