name: MyLover Continuous Integration
on:
    push:
        branches: [ money-lover ]
jobs:
    build:
        name: Post welcome comment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
                with:
                node-version: 18
